type demo  {
    id: String!
    version: String!
}
type Query @aws_api_key {
    getDemos: [ demo! ]
    getDemosRds: [ demo! ]
}

type job {
    id: String!
    version: String!
}

input DemoInput {
    version: String!
}

type Mutation @aws_api_key @aws_iam {
    addDemo(input: DemoInput!): demo
    addDemoRds(input: DemoInput!): demo
    callStepFunction(input: DemoInput!): job
}


